name: Tests
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: System Setup
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -qq lua5.3-dev
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          make test
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          make test
