---
name: Tests
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: System Setup
        shell: bash
        run: |
          wget http://www.lua.org/ftp/lua-5.4.4.tar.gz
          tar xvfz lua-5.4.4.tar.gz
          cd lua-5.4.4
          sed -i 's/MYCFLAGS=/MYCFLAGS=-fpic/g' src/Makefile # relocation R_X86_64_PC32 against symbol `lua_newstate' can not be used when making a shared object; recompile with -fPIC
          make
          sudo make install
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          sudo make install
          sudo ldconfig
          sudo make test
#   macos:
#     name: macOS
#     runs-on: macos-latest
#     steps:
#       - name: System Setup
#         shell: bash
#         run: |
#           wget http://www.lua.org/ftp/lua-5.4.4.tar.gz
#           tar xvfz lua-5.4.4.tar.gz
#           cd lua-5.4.4
#           # sed -i '' 's/MYCFLAGS=/MYCFLAGS=-fpic/g' src/Makefile
#           make
#           sudo make install
#       - uses: actions/checkout@v2
#       - name: Run Tests
#         run: |
#           export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib
#           ls -la /usr/local/lib
#           echo $DYLD_LIBRARY_PATH
#           sudo make install
#           sudo make test
