name: Tests
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: System Setup
        shell: bash
        run: |
          sudo apt update -y
          wget http://www.lua.org/ftp/lua-5.4.4.tar.gz
          tar xvfz lua-5.4.4.tar.gz
          cd lua-5.4.4
          make linux install
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          make test
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: System Setup
        shell: bash
        run: |
          sudo apt update -y
          wget http://www.lua.org/ftp/lua-5.4.4.tar.gz
          tar xvfz lua-5.4.4.tar.gz
          cd lua-5.4.4
          make macos install
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          make test
